### ISSUE TITLE
JsonSerDe serialization and deserialization inconsistency 

### ISSUE THREAD

**Issue by MichalPerschke** [DreamLab/memoize#11]
Hi, there is a problem with JsonSerDe, when your local timezone is other than UTC, when you serialialize and deserialize your entry, the dates are different. It causes the Cache doesn't work with expiration dates correctly

**Comment by zmumi** [comment]
Quite a while passed - maybe it's no longer relevant, but how did you solve/avoid the issue? Maybe this pattern could be applied to the library itself?

**Comment by zmumi** [comment]
Please reopen if the issue persists
