### ISSUE TITLE
[Question] Blocking on update

### ISSUE THREAD

**Issue by dreo** [DreamLab/memoize#12]
Hi folks,

currently when a cached value is being recomputed, the expired value is returned until it's replaced by the new one. Is there a way to configure memoize so that the call is blocking in the same way as when no value is available?

One way to get this working might be altering `get` method in the storage:
```
    async def get(self, key: CacheKey) -> Optional[CacheEntry]:
        entry = self._data.get(key, None)
        if entry:
            if entry.expires_after <= datetime.datetime.utcnow():
                await self.release(key)
                entry = None
        return entry
```
But it feels like a dirty hack. The other way might be re-implementing the responsible part of the wrapper, specifically this part:
```
        elif actual_entry is not None and update_statuses.is_being_updated(key):
            logger.debug('As update point reached but concurrent update already in progress, '
                         'relying on concurrent refresh to finish %s', key)
            return actual_entry
```
What I'm looking for is a 'proper' way to do this. Could you suggest one? Thanks!

edit: code error

**Comment by dreo** [comment]
In other words, what I'm looking for is how to make sure that memoize never ever returns an expired value.

**Comment by zmumi** [comment]
Or maybe there should be something more explicit. For now, let me know if that helps

**Comment by dreo** [comment]
Thanks for a super quick reply!

Interestingly, I doesn't seem to work the same way for me, even with the `expire_after` being lower. 

I'm starting two async tasks at the exactly same time (using `apscheduler` - but that should be just a detail). Both tasks request the same data from cache, at that time the data is expired. I'm consistently getting fresh value in one task and expired value in the other, the order is random however. When I enable debug prints, I see this:

1. (2 tasks executed)
2. memoize: "Entry expiration reached - entry update (blocking) for key .... "
3. memoize: "As update point reached but concurrent update already in progress, relying on concurrent refresh to finish ... " (data requested from the second task)
4. (expired value is returned to the first task, execution continues, the other task is still blocked)
5. (+2 sec, new value computed)
6. memoize: "Successfully refreshed cache for key ... "
7. New value returned to the second task, execution of the second task continues

Not sure it that's clear, I can provide more details if needed.

**Comment by dreo** [comment]
What seems to be interesting is the message "relying on concurrent refresh to finish", which to me sounds rather like a blocking wait was intended to follow, but instead the expired value is directly returned here.

**Comment by zmumi** [comment]
You are right - I was able to replicate that with 
```
EXPIRATION = 20
QUERY_DELAY = 30
RESPONSE_DELAY = 10


@memoize(configuration=DefaultInMemoryCacheConfiguration(
    expire_after=timedelta(milliseconds=EXPIRATION),
    update_after=timedelta(days=1)  # dummy value - it should just be larger than expire_after
))
async def expensive_computation():
    await asyncio.sleep(RESPONSE_DELAY / 1000)
    return 'expensive-computation-' + str(random.randint(1, 100))


async def main():
    for i in range(10):
        print(await asyncio.gather(expensive_computation(), expensive_computation(), expensive_computation()))
        await asyncio.sleep(QUERY_DELAY / 1000)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

I'm working on a fix - it should be quite simple and you could try that out with https://pypi.org/project/py-memoize/1.1.1b1/

**Comment by zmumi** [comment]
Glad it works - thanks for reporting!
