### ISSUE TITLE
Tests failing with python 3.10

### ISSUE THREAD

**Issue by sdelafond** [DreamLab/memoize#15]
From https://bugs.debian.org/1002199 :

> ======================================================================
> ERROR: memoize (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: memoize
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
>     package = self._get_module_from_name(name)
>   File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
>     __import__(name)
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pymemoize/build/memoize/__init__.py", line 1, in <module>
>     from .core import Memoizer
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pymemoize/build/memoize/core.py", line 4, in <module>
>     from .func import MemoizedFunction
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pymemoize/build/memoize/func.py", line 9, in <module>
>     from .options import OptionProperty
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_pymemoize/build/memoize/options.py", line 2, in <module>
>     from collections import Callable
> ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

Is there any interest in supporting python 3.10 ?

**Comment by zmumi** [comment]
@sdelafond I believe you are referring to another project https://github.com/mikeboers/PyMemoize/blob/b10f0d8937e519353a980b41c4a1243d7049133a/memoize/options.py#L2

**Comment by zmumi** [comment]
For anyone else interested I'm proceeding with compatibility in this project tests (as they happen also to be broken)
- pull request https://github.com/DreamLab/memoize/pull/16 (WIP)
- beta release https://pypi.org/project/py-memoize/1.1.2b1/

The workaround is rather brute but test setup based on `tornado.testing` is rater fragile and probably should be replaced by something else in the long run.

**Comment by sdelafond** [comment]
> @sdelafond I believe you are referring to another project https://github.com/mikeboers/PyMemoize/blob/b10f0d8937e519353a980b41c4a1243d7049133a/memoize/options.py#L2

You're right, sorry for the mixup.

**Comment by zmumi** [comment]
python 3.10 support has been added
