### ISSUE TITLE
[Question] Does this library work with gevent (including dog-piling mitigation)?

### ISSUE THREAD

**Issue by altaha** [DreamLab/memoize#4]
Hi,
I came across this library when I was looking up ways to mitigate dog-piling when using gevent (with gunicorn), but the docs only talk about Asyncio and Tornado support, but no mention of gevent/greenlets. Would this library work with gevent? because I believe gevent would lead to the same dog-piling issue if I need to refresh the cache using a request to an external API that takes a few seconds.

Thanks for the great work!

**Comment by zmumi** [comment]
Hi,
There is no integration with gevent/greenlets. I believe it won't work out-of-the-box unfortunately.
You could take a look at integrating asyncio with gevent (as mentioned there https://github.com/gevent/gevent/issues/982 ).
If you'll see some success, please share!

**Comment by zmumi** [comment]
not planning integration with gevent
